### ISSUE TITLE
Support iOS 14

### ISSUE THREAD

**Issue by daikimat** [cybozu/AttachmentInput#27]

**Comment by elmetal** [comment]
In this switch statement, im getting an error on Xcode12 beta.
https://github.com/cybozu/AttachmentInput/blob/master/AttachmentInput/AttachmentInput/Logic/ImagePickerAuthorization.swift#L74-L85

added cases `.limited`
https://developer.apple.com/documentation/photokit/phauthorizationstatus?changes=latest_minor

**Comment by daikimat** [comment]
released
https://github.com/cybozu/AttachmentInput/releases/tag/0.0.3

<img width="368" alt="ss" src="https://user-images.githubusercontent.com/32447102/86695416-7a94bb00-c047-11ea-8cf5-66eb0a9308ec.png">
