### ISSUE TITLE
support more than once photo picker time

### ISSUE THREAD

**Issue by fukemy** [cybozu/AttachmentInput#33]
hi, thanks for great lib, did u support multi image picker? Thanks

**Comment by daikimat** [comment]
@fukemy 
Sorry for replying late.
The selection of multiple images is originally supported by version 0.0.4.
If you're talking about the `limited photos picker` of iOS 14, we've released 0.0.5 to support it.
Thanks.

**Comment by fukemy** [comment]
ok i know it, thanks
